# Generated by Django 3.2.3 on 2021-07-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_alter_fcuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('admin', '관리자'), ('user', '사용자')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
